name: Update sing-box rule-set

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-rule-set:
    name: Update sing-box rule-set
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup sing-box
        env:
          SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.8.4/sing-box_1.8.4_linux_amd64.deb"
        run: |
          set -Eeuo pipefail
          wget -O sing-box.deb $SING_BOX_DEB_URL
          sudo dpkg -i sing-box.deb

      - name: Setup python venv
        run: |
          set -Eeuo pipefail
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt

      - name: Update rule-set
        run: |
          set -Eeuo pipefail
          source venv/bin/activate
          python3 generate_rule_set.py

      - name: Update README.md
        uses: muesli/readme-scribe@master
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "github-profile.tpl" # Chỉ định đường dẫn chính xác của temple
          writeTo: "README.md"

      - name: Commit and push
        run: |
          set -Eeuo pipefail
          cd rule-set
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --allow-empty-message --no-edit
          git branch -M rule-set
          git remote add origin https://github.com/Thaomtam/sing-box-rule-set-vn.git
          git push -u origin rule-set --force
